import { expect, test } from '@playwright/test';
import { FIXTURE_LISTING, uniqueHandle } from './db-fixtures';

// Uses the listing published by db-setup.spec.ts and registers its own buyer.
test('register, draft, profile persistence and session boundaries', async ({ page }) => {
  const handle = uniqueHandle('buyer');
  const password = 'browser-buyer-password-123';
  await page.goto('/register');
  await page.getByLabel('Handle', { exact: true }).fill(handle);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Create account' }).click();
  await expect(page.locator('.account-name')).toHaveText(handle);
  await page.getByRole('link', { name: FIXTURE_LISTING, exact: true }).click();
  await page.getByRole('link', { name: 'Review order draft' }).click();
  await page.getByLabel('Reference currency').selectOption('XMR');
  await page.getByRole('button', { name: 'Create unfunded draft' }).click();
  await expect(page).toHaveURL(/\/order\?id=/);
  await expect(page.getByRole('heading', { name: 'Payment is unavailable' })).toBeVisible();
  await expect(page.locator('.total')).toContainText('XMR');
  await expect(page.locator('.page-head .badge')).toHaveText('Draft — unfunded');
  expect((await page.goto('/admin'))?.status()).toBe(403);
  await page.goto('/account');
  await page.getByLabel('XMPP address').fill(`${handle}@example.test`);
  await page.getByRole('button', { name: 'Save profile' }).click();
  await page.reload();
  await expect(page.getByLabel('XMPP address')).toHaveValue(`${handle}@example.test`);
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await page.goto('/account');
  await expect(page).toHaveURL(/\/login$/);
  await page.getByLabel('Handle', { exact: true }).fill(handle);
  await page.getByLabel('Password', { exact: true }).fill('wrong-password-123');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await expect(page.locator('body')).toContainText('Invalid handle or password');
  await page.goto('/login');
  await page.getByLabel('Handle', { exact: true }).fill(handle);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.goto('/account');
  await expect(page.getByLabel('XMPP address')).toHaveValue(`${handle}@example.test`);
});
