import { createHmac } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { expect, type Browser, type Locator, type Page } from '@playwright/test';

// Shared helpers for the database specs that submit real forms with JavaScript disabled.

// Committed OpenPGP fixtures (tests/e2e/fixtures/pgp/). No OpenPGP package is installed for the browser tests,
// so these were generated once with github.com/ProtonMail/go-crypto v1.4.1 (the library the server uses) from two
// throwaway Ed25519/X25519 keys whose private halves were discarded. They cannot be regenerated byte-for-byte and
// nobody can sign or decrypt with these keys any more:
//   recipient.pub.asc           "E2E Fixture Recipient" public key (fingerprint RECIPIENT_FINGERPRINT)
//   other.pub.asc               "E2E Fixture Other" public key
//   message-to-recipient.asc    a real OpenPGP message encrypted to the recipient key
//   stale-challenge.signed.asc  the recipient key's clearsignature over an ownership challenge for another handle
//   canary.recipient-key.asc    a canary statement clearsigned by the recipient key (valid for that operator key)
//   canary.other-key.asc        the same statement clearsigned by the other key (invalid for the recipient key)
export const RECIPIENT_FINGERPRINT = 'CB92 A044 56D0 95A3 5DE4 C354 770D ADF2 A2D7 0ABB';

export function pgpFixture(name: string): string {
  return readFileSync(join(__dirname, 'fixtures', 'pgp', name), 'utf8');
}

// A fresh JavaScript-disabled browser context that registers (or signs in as) handle.
export async function signedIn(browser: Browser, baseURL: string | undefined, handle: string, password: string, register: boolean, width = 390): Promise<Page> {
  const context = await browser.newContext({ baseURL, javaScriptEnabled: false, viewport: { width, height: 900 } });
  const page = await context.newPage();
  await page.goto(register ? '/register' : '/login');
  await page.getByLabel('Handle', { exact: true }).fill(handle);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: register ? 'Create account' : 'Sign in' }).click();
  await expect(page.locator('.account-name')).toHaveText(handle);
  return page;
}

// Submits the admin "Assign an account role" form for handle.
export async function setRole(admin: Page, handle: string, role: string) {
  await admin.goto('/admin');
  const form = admin.locator('form', { has: admin.getByRole('button', { name: 'Update role' }) });
  const option = form.locator('option', { hasText: `${handle} ·` });
  await form.getByLabel('Account').selectOption(await option.getAttribute('value'));
  await form.getByLabel('Role').selectOption(role);
  await form.getByRole('button', { name: 'Update role' }).click();
  await expect(admin).toHaveURL(/\/admin\?saved=1$/);
}

// Clicks a submit button and returns the HTTP status of the navigation it causes. Refused actions answer
// with a plain-text error page (http.Error), which is what a no-JavaScript browser shows the user.
export async function submitStatus(page: Page, click: () => Promise<void>): Promise<number> {
  const [response] = await Promise.all([
    page.waitForResponse(r => r.request().method() === 'POST' && r.request().isNavigationRequest()),
    click(),
  ]);
  return response.status();
}

// Submits a form and waits for the resulting page to load, so a following reload cannot race the in-flight
// POST and its redirect ("Not attached to an active page").
export async function submitAndLoad(page: Page, button: Locator): Promise<void> {
  await Promise.all([page.waitForEvent('load'), button.click()]);
}

// RFC 6238 (SHA-1, 30 s, 6 digits) code for a displayed base32 secret at a given 30-second step.
export function totp(secret: string, step: number): string {
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
  let bits = 0, value = 0;
  const key: number[] = [];
  for (const ch of secret.toUpperCase().replace(/[\s=]/g, '')) {
    value = (value << 5) | alphabet.indexOf(ch);
    bits += 5;
    if (bits >= 8) {
      key.push((value >>> (bits - 8)) & 0xff);
      bits -= 8;
    }
  }
  const counter = Buffer.alloc(8);
  counter.writeBigUInt64BE(BigInt(step));
  const mac = createHmac('sha1', Buffer.from(key)).update(counter).digest();
  const offset = mac[mac.length - 1] & 0x0f;
  return ((mac.readUInt32BE(offset) & 0x7fffffff) % 1_000_000).toString().padStart(6, '0');
}

// Enrolls TOTP on /totp for the signed-in page with the current step's code and returns the secret.
export async function enrollTOTP(page: Page): Promise<string> {
  await page.goto('/totp');
  await page.getByRole('button', { name: 'Start enrollment ↗' }).click();
  const secret = (await page.locator('.totp-secret').innerText()).replace(/\s+/g, '');
  await page.getByLabel('6-digit code from your app').fill(totp(secret, Math.floor(Date.now() / 30_000)));
  await page.getByRole('button', { name: 'Verify and turn on ↗' }).click();
  await expect(page.locator('.page-head .badge')).toHaveText('Enabled');
  return secret;
}
